---
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-09d95fab7fff3776c # latest id from `Choose AMI` screen
      InstanceType: t2.micro
