AWSTemplateFormatVersion: 2010-09-09
Parameters:
    AMIId:
        Type: String
        Default: 'ami-09d95fab7fff3776c'
        Description: 'Name of existing EC2 AMI ID'
    KeyName:
        Type: 'AWS::EC2::KeyPair::KeyName'
        Description: 'Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter'
        ConstraintDescription: Must be the name of an existing EC2 KeyPair
    CIDRInboundTCPIP:
        Type: String
        Description: 'Enter the inbound allowed CIDR Ip address for TCP port EC2 instance'
        MinLength: '9'
        MaxLength: '18'
        Default: 0.0.0.0/0
        AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    CIDRInboundSSHIP:
        Type: String
        Description: 'Enter the inbound allowed CIDR Ip address for SSH port EC2 instance'
        MinLength: '9'
        MaxLength: '18'
        Default: 0.0.0.0/0
        AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
Resources:
  EC2EIPMain:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Main
  EC2Main:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref AMIId
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref SGMain1
  SGMain1:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: 'Default Parametarized SG'
        SecurityGroupIngress:
            -   CidrIp: !Ref CIDRInboundTCPIP
                Description: 'TCP Inbound'
                FromPort: 80
                IpProtocol: tcp
                ToPort: 80
            -   CidrIp: !Ref CIDRInboundSSHIP
                Description: 'SSH Inbound'
                FromPort: 22
                IpProtocol: tcp
                ToPort: 22
